# Project
site_name: Notebook of Dexter

# theme
theme:
  name: material #mkdocs #material #readthedocs
  language: en
  logo: logo.jpg
  favicon: logo.jpg
  palette:
    scheme: default
    primary: black
  features:
    - navigation.top
    - navigation.tabs
  font: false # google font load failed

# Extension
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra
extra:
  pagetime: "on"

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: 'Copyright &copy; 2018 - 2024 Dexter Personal'